# Generated by Django 6.0.3 on 2026-04-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noaiapplication', '0002_student_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('shirt_size', models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'Large')], max_length=1)),
            ],
        ),
    ]
