# Generated by Django 5.1.13 on 2026-04-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noaiapplication', '0004_apple_group_manufacture_question_runner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(default='zero')),
            ],
        ),
    ]
