# Generated by Django 5.1.13 on 2026-04-05 23:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noaiapplication', '0006_customer_persondemo_productdemo_person_shirt_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdemo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
